version: '3'
services:
  python:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: 'python-river-proj'
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    tty: true